# Generated by Django 3.1.3 on 2020-11-18 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='long_desc',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='short_desc',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
