# Generated by Django 3.1.3 on 2020-11-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_total_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='percent',
            field=models.FloatField(default=0),
        ),
    ]
